# fly.toml app configuration file generated for sge-api-main on 2025-03-24T13:18:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sge-api-main'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
